config/routes.rb
Rails.application.routes.draw do
  get 'customers/alphabetized'
  get 'customers/missing_email'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
   root "customers#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  def self.ransackable_attributes(auth_object = nil)
    excluded_attributes = ['id', 'encrypted_password', 'password_reset_token', 'reset_password_sent_at', 'remember_created_at', 'sign_in_count', 'current_sign_in_at', 'last_sign_in_at', 'current_sign_in_ip', 'last_sign_in_ip', 'confirmation_token', 'confirmed_at', 'confirmation_sent_at', 'unconfirmed_email', 'failed_attempts', 'unlock_token', 'locked_at', 'owner']
    (column_names - excluded_attributes).sort
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "full_name", "id", "id_value", "notes", "phone_number", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["image_attachment", "image_blob"]
  end

  has_one_attached :image

  validates :full_name, presence: true
  validates :phone_number, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def alphabetized
    @customers = Customer.order(:full_name)
  end

  def missing_email
    @customers = Customer.where("email = ''" )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer.html.erb
<div class="container">
  <div class="columns is-multiline is-justify-content-center">
    <% @customers.each do |customer| %>
      <div class="column is-4 equal-height">
        <div class="box">
          <h1 class="title is-4 has-text-centered"><%= customer.full_name %></h1>
          <div class="has-text-centered">
            <%= image_tag(customer.image, width: 100) if customer.image.attached? %>
          </div>
          <ul class="mt-3">
            <li><strong>Email:</strong> <%= customer.email.presence || "NONE" %></li>
            <li><strong>Phone:</strong> <%= customer.phone_number %></li>
            <li><strong>Notes: </strong><%= customer.notes.presence || "NONE" %></li>
          </ul>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/customers/_nav.html.erb
<nav class="is-flex is-justify-content-center">
  <ul class="is-flex">
    <li class="mr-3"><%= link_to 'All Customers', root_path %></li>
    <li class="mr-3"><%= link_to 'Alphabetized Customers', customers_alphabetized_path %></li>
    <li><%= link_to 'Missing Email Customers', customers_missing_email_path %></li>
  </ul>
</nav>

app/views/customers/alphabetized.html.erb
<h1 class="title is-1 has-text-centered">Alphabetized Customers</h1>
<%= render partial: "nav"%>
<%= render partial: "customer"%>

app/views/customers/index.html.erb
<h1 class="title is-1 has-text-centered">All Customers</h1>
<%= render partial: "nav"%>
<%= render partial: "customer"%>

app/views/customers/missing_email.html.erb
<h1 class="title is-1 has-text-centered">Missing Email Customers</h1>
<%= render partial: "nav"%>
<%= render partial: "customer"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>